### ISSUE TITLE
Does not restart the previous run

### ISSUE THREAD

**Issue by subha18** [clrp-code/egs_brachy#12]
Hello
After completing a simulation for smaller no. of histories, would like to restart the run for larger no. of histories as used to do in other user codes (ex: dosrznrc)

As defined in technical manual of egs_brachy i have added
calculation = restart  in run control

It seem it does find the .egsdat file. However it is available in dir egs_brachy.
i am getting the following error:
**EGS_Application::readData: failed to open /home/mcarlo/egs/EGSnrc/egs_home/egs_brachy/egsrun_26882_Ir192_Varisource_2000_TG43_mcarlo/Ir192_Varisource_2000_TG43.egsdat for writing
EGS_Application::runSimulation(): failed to start the simulation**

**Comment by mchamberland** [comment]
Indeed, this is a bug. We will fix it. Thank you for your patience!

Note to self: the `restart` option is meant to restart a _completed_ simulation. A completed simulation's `egsdat` file lives in the application folder and not in the `egsrun_*` folders. 

Thus, [this call](https://github.com/clrp-code/egs_brachy/blob/d30745354209ebc6c3a39e97c87ef45d5ea5ccbd/egs_brachy/egs_brachy.cpp#L2397) to `constructIOFilename()` should be done with `with_run_dir` set to `false`.

**Comment by mchamberland** [comment]
Fixed, but note that some of the numbers reported in the egslog (e.g., number of steps taken) will be reported wrong for a restarted simulation. The actual doses are correct, though.
