### ISSUE TITLE
Inconsistent restrictions on density correction files

### ISSUE THREAD

**Issue by rtownson** [clrp-code/egs_brachy#13]
A user recently reported issues with their density correction files that they tracked down to be egs_brachy specific. In order to add their own density correction files they had to place them in the HEN_HOUSE (usually they should go in egs_home) and follow a stricter file format.

Here are their conclusions:

> In order to get it working, we needed to fix several things. First of all, the density correction files need to be in:
> 
> EGSnrc_with_egs_brachy/HEN_HOUSE/pegs4/density_corrections
> 
> Placing them in egs_home/pegs4/density did not resolve the issue.
> 
> Secondly, egs_brachy is sensitive to spaces/tabs  in the second line of the density correction files.
> While regular XYZ geometry simulations are flexible to space/tabs, it is not the case for egs_brachy.
> There should  be 7, 3,7,14-16 spaces between
>        numberOfEnergies    meanIonizationEnergy       density             numberOfElements
> 
> NO TABS!
> 
> 
> After this everything seems to work fine.

**Comment by mchamberland** [comment]
I'm fairly certain egs_brachy does not handle density corrections by itself, so the issue should be with the main EGSnrc code.

One possibility is that the EGSnrc version that egs_brachy comes bundled with is out of date with the NRC master branch...

**Comment by mchamberland** [comment]
All of those issues remind me of the commits from circa 2016 that addressed all of this in the NRC repo. All of those commits are in our fork of EGSnrc.

I can try reproducing the issue, but I suspect I won't be able to and this user's EGSnrc code is somehow out of date.

**Comment by rtownson** [comment]
I'm pretty sure that you're right, that they installed egs_brachy on an existing EGSnrc repository. I can follow up with them to see if that was the case.

**Comment by rtownson** [comment]
So they got back to me, and they installed by cloning this repository this year. Also, the density correction file issue only appears when they use a phantom like the following. If they use simple geometries or the standard EGSnrc XYZ geometry to load the egsphant file, there is no issue.

```
    :start geometry:             #phantom will be defined by the egsphant file 
                                 #(derived from DICOM-CT data from test case)
        name = phantom
        library = egs_glib
        type = egsphant
        egsphant file =/home/alex/egsnrc_mp/ctcreate/noShielding/noShielding.txt.egsphant
	density file = lib/media/material_AS.dat    
             # the .medialist file lists all media in the egsphant, 
             # along with their nominal densities (note that voxel-by-voxel 
             # densities may vary).
    :stop geometry:
```

**Comment by mchamberland** [comment]
Aaaah! Ok, yes, there definitely might be something here.

I guess my question would be: does this problem show up in other applications? For example, in tutor7pp, if they load an egsphant with egs_glib as above?

I’ll try it sometime this week or this weekend, but if they can give it a shot, that would be great. 

In the meantime, paging @randlet, in case he has an idea off the top of his head.

**Comment by mchamberland** [comment]
This is related to a feature of egs_glib (so, not egs_brachy, technically) that we stripped out before including in the NRC EGSnrc repo. I forget the details of why we stripped it out of the PR, though.

**Comment by rtownson** [comment]
The egsphant loading was removed from egs_glib because it seemed to duplicate functionality already in the XYZ geometry. However, I see now that it has extra functionality, so maybe this was not the right course. Ideally it could all get swept up into the XYZ implementation? Anyways, that's another issue..

**Comment by mchamberland** [comment]
That's right, we wanted to avoid the duplication of features, but then we realized we had extra features relative to the main NRC repo. So we just restored the functionality in our version of egs_glib in the meantime.

Yes, ideally we should try to sweep it into the XYZ implementation.

**Comment by randlet** [comment]
Hi guys, looks like you have most of the history but just FYI I dug through some old emails and found this discussion (from Rowan):

> We've been unable to use egsphant files via the EGS_XYZGeometry feature
> of the egs_nd_geometry.  
>
> The problem seems to be that the relevant code egs_nd_geometry.h uses the
> ramp file to "defines mass density to medium
> conversion rules" (egs_nd_geometry.h); however, for many of the phantoms
> we use in
> brachytherapy simulations, we assign media not only based on density but
> also physician contours -- there is a degeneracy in mass densities, ie
> more than one tissue can have the same mass density.  (We typically derive
> egsphant files from DICOM-CT data using in-house routines.)
> 
> In principle, this ramp file shouldn't be needed because mass densities
> are already specified in the egsphant file

and my response:

> I agree, the simplest short term solution is to just re-include the functionality in egs_glib for now.  Marc also pointed out a while ago (https://github.com/randlet/egs_brachy/commit/52e97c3e04bb328b1faee3b2bee4f0e78a20eca7#commitcomment-20645882) that it in the egs_glib version it was nice to be able to use a PEGS4 data file to pull densities from instead of having to create a separate density file.  It's simple enough to keep that egs_glib feature just in the egs_brachy branch for now and then talk to NRC about either updating the XYZ geometry to handle this, or leaving the feature in egs_glib.

I don't have time to help port the egs_glib stuff over to the XYZ geometry right now unfortunately.

**Comment by randlet** [comment]
I think that repo/commit in my comment is private so here's the discussion:

From Marc:

> One of the neat things about the previous implementation was that the 'density file' could simply be a PEGS4 file. The format of the ramp file is a little different, however. Any chance you can whip out a little utility to convert PEGS4 and material.dat files to a ct ramp file, assuming min density = max density = default density?

> And if we end up distributing egsphant files, then we should also distribute a corresponding ramp file.

From me:
> Before egs_glib had egsphant support I wrote https://github.com/randlet/egsphant2egspp to convert egsphant to egspp binary format & ramp file, so that might be useful too. But, yes, should be simple to do the same for pegs4 & material.dat files.
>
> I agree it was a nice that you could just use pegs4 or material.dat file directly, but I agree with Reid that it's maybe better to only have a single geometry that loads egsphant files.

**Comment by rtownson** [comment]
Just to add to this - we entirely intend to remove the use of ramp files for egsphant, since it's not needed.

I can help with bringing these features into EGSnrc (eventually..), I mostly just wanted to raise awareness about this user's issue and get some feedback.

**Comment by mchamberland** [comment]
Looking at the current code, it appears to be searching the same paths as EGSnrc and it has no hard-coding of spaces, so I'll chalk this up to "cannot reproduce".

If someone can provide input files where this is reproducible, feel free to open a new issue and I'll take another look.
