### ISSUE TITLE
egs++ getMass behaviour will change in EGSnrc 2022 release

### ISSUE THREAD

**Issue by randlet** [clrp-code/egs_brachy#14]
See: https://github.com/nrc-cnrc/EGSnrc/issues/720

I think this just means we will need to update the getUncorrectedVolume function here: https://github.com/clrp-code/egs_brachy/blob/egs_brachy_2020/egs_brachy/phantom.cpp#L302

**Comment by MartinMartinov** [comment]
Updated in commit: cc2e1610a5a22559ae2550720ed6712d0f037cdd
