### ISSUE TITLE
Using "include file" input for MC parameters causes an error

### ISSUE THREAD

**Issue by MartinMartinov** [clrp-code/egs_brachy#23]
When importing values from low_energy_default, there is an error on bremsstrahlung correction that reads:

INPUT-->NRC <--NOT ALLOWED
OPTIONS ARE:
                                                                       KM
                                                                     NRC
                                                                  NONE

**Comment by MartinMartinov** [comment]
Best guess is the importing code adds a space at the end of the line which causes the above issue, do not currently have time to investigate.

**Comment by mchamberland** [comment]
Cannot reproduce and the `include file` code is part of `egs++`, not `egs_brachy`.
