### ISSUE TITLE
Failed compiling egs_c_utils.h and egs_c_utils.c in installation of egs_brachy in windows 

### ISSUE THREAD

**Issue by ROUZII3** [clrp-code/egs_brachy#61]
I am new to EGS and seeking assistance with installing EGS_brachy on my Windows 10 system to conduct simulations in brachytherapy. While following the EGS_brachy manual, I encountered an error during the configuration of EGSnrc using the configuration shell script (./HEN_House/scripts/configure). Despite following the provided instructions and attempting to adjust the GCC version, the compilation of egs_c_utils.c and egs_c_utils.h failed. And it gave me this recommandations:
Creating egs_c_utils.h and egs_c_utils.c ...      OK
Compiling egs_c_utils.c ...                       Failed

Failed to compile egs_c_utils.c. This may be due to a variety of reasons
(e.g., non-standard include files, unsupported file lock operations, etc.
Will disable now the availability of a C compiler.
If you want to try to make the new parallel processing implementation in
cavrznrc and dosrznrc work,
  1. Go to /c/EGSnrc_CLRP/HEN_HOUSE/lib/mingw64_nt-10.0-19045
  2. Edit egs_c_utils.h and egs_c_utils.c to make them compile with your
     C compiler
  3. Put
     REPLACE {$HAVE_C_COMPILER(#);} WITH {{EMIT;{P1}define HAVE_C_COMPILER};}
     in machine.macros
  4. Put
     $HAVE_C_COMPILER(#);
     near the beginning of your user-code.
  5. If your compiler requires some unusual options, include directives, etc.,
     change the variable C_FLAGS in the spec file mingw64_nt-10.0-19045.conf in the
     /c/EGSnrc_CLRP/HEN_HOUSE/specs/ directory.
I would greatly appreciate any guidance or suggestions to resolve this persistent issue.
[the.error.msg.txt](https://github.com/clrp-code/egs_brachy/files/14481222/the.error.msg.txt)
[configure.txt](https://github.com/clrp-code/egs_brachy/files/14481224/configure.txt)

**Comment by mchamberland** [comment]
Technically, this is an EGSnrc issue, not an egs_brachy-specific one. Please ask for help on [the main EGSnrc repository](https://github.com/nrc-cnrc/EGSnrc/discussions).
