### ISSUE TITLE
Output egsphant does not handle more than 10 media

### ISSUE THREAD

**Issue by mchamberland** [clrp-code/egs_brachy#7]
Issue comes from [this line](https://github.com/clrp-code/egs_brachy/blob/master/egs_brachy/phantom.cpp#L626). When an egsphant has more than 10 media, the media keys go to letters ('A', 'B', 'C', etc.) and not to numbers ('10', '11', etc.).

**Comment by mchamberland** [comment]
I can't find the key used to map media in an egsphant, but I think they go: 123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ.

**Comment by randlet** [comment]
@mchamberland I just pushed a fix in 4dd741dbb75 (in vol_unc branch).

**Comment by mchamberland** [comment]
@randlet  Thanks! I think you haven't pushed it yet (at least, I don't see it...).

**Comment by randlet** [comment]
Lol.  Sorry!  It's pushed now.
